[package]
name = "scheduler"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
train_lib = { path = "../shared" }
log = "0.4.16"
env_logger = "0.9.0"
redis = "0.23.3"
