---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scheduler
  labels:
    shepherd.run/uses-postgres: "true"
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: scheduler
  template:
    metadata:
      labels:
        app.kubernetes.io/name: scheduler
    spec:
      containers:
        - name: scheduler
          image: localhost:5000/scheduler
          imagePullPolicy: IfNotPresent 
          env:
            - name: RUST_LOG
              value: info
