---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reconciller
  labels:
    shepherd.run/uses-postgres: "true"
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: reconciller
  template:
    metadata:
      labels:
        app.kubernetes.io/name: reconciller
    spec:
      containers:
        - name: reconciller
          image: localhost:5000/reconciller
          imagePullPolicy: IfNotPresent 
          env:
            - name: RUST_LOG
              value: info
