apiVersion: v1
kind: Pod
metadata:
  name: train-api
  labels:
    app.kubernetes.io/name: train-api
spec:
  containers:
  - name: train-api 
    image: localhost:5000/api
    env:
      - name: RUST_LOG
        value: info
    ports:
    - containerPort: 3200
      name: train-api-port
---
apiVersion: v1
kind: Service
metadata:
  name: train-api
spec:
  selector:
    app.kubernetes.io/name: train-api
  ports:
  - name: train-service-port
    protocol: TCP
    port: 80
    targetPort: train-api-port
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: train-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: /train(/|$)(.*)
        backend:
          service:
            name: train-api
            port:
              number: 80
