---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scheduler
  labels:
    shepherd.run/uses-postgres: "true"
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: scheduler
  template:
    metadata:
      labels:
        app.kubernetes.io/name: scheduler
    spec:
      containers:
        - name: scheduler
          image: localhost:5000/scheduler
          env:
            - name: RUST_LOG
              value: info
          volumeMounts:
            - name: conf
              mountPath: /root/.kube
      volumes:
        - name: conf
          secret:
            secretName: kube-config # create the secret with the key `config` from the file `~/.kube/config`
