VERSION 0.7

src:
    FROM rust
    COPY  ./src reconciller/src/
    COPY Cargo.toml reconciller/
    COPY ../shared+src/shared shared
    SAVE ARTIFACT reconciller

build:
    FROM +src
    WORKDIR /reconciller/
    RUN cargo build -r
    SAVE ARTIFACT target/release/reconciller

image:
    # FROM --platform=linux/amd64 gcr.io/distroless/static:nonroot
    # FROM debian:stable-20200803-slim
    FROM rust
    RUN apt-get update && apt-get install -y jq
    RUN curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl" \
        && install kubectl /usr/local/bin/ \
	&& rm kubectl
    RUN curl -LO "https://github.com/tektoncd/cli/releases/download/v0.33.0/tektoncd-cli-0.33.0_Linux-64bit.deb" \
        && dpkg -i tektoncd-cli-0.33.0_Linux-64bit.deb \
	&& rm tektoncd-cli-0.33.0_Linux-64bit.deb

    COPY +build/reconciller  /usr/local/bin/
    ENTRYPOINT ["/usr/local/bin/reconciller"]
    SAVE IMAGE reconciller
