VERSION 0.7

src:
    FROM rust
    COPY  ./src reconciller/src/
    COPY Cargo.toml reconciller/
    COPY ../shared+src/shared shared
    SAVE ARTIFACT reconciller

build:
    FROM +src
    WORKDIR /reconciller/
    RUN cargo build -r
    SAVE ARTIFACT target/release/reconciller

image:
    # FROM --platform=linux/amd64 gcr.io/distroless/static:nonroot
    # FROM debian:stable-20200803-slim
    FROM rust
    RUN apt-get update \
        && apt-get install -y gnupg \
        && mkdir -p /root/.gnupg/ \
        && mkdir -p /etc/apt/keyrings/ \
        && gpg --no-default-keyring --keyring /etc/apt/keyrings/tektoncd.gpg --keyserver keyserver.ubuntu.com --recv-keys 3EFE0E0A2F2F60AA \
        && echo "deb [signed-by=/etc/apt/keyrings/tektoncd.gpg] http://ppa.launchpad.net/tektoncd/cli/ubuntu eoan main" | tee /etc/apt/sources.list.d/tektoncd-ubuntu-cli.list \
        && apt-get update \
        && apt-get install -y tektoncd-cli

    COPY +build/reconciller  /usr/local/bin/
    ENTRYPOINT ["/usr/local/bin/reconciller"]
    SAVE IMAGE reconciller
