VERSION 0.7

src:
    FROM rust
    COPY  ./src api/src/
    COPY Cargo.toml api/
    COPY ../shared+src/shared shared
    SAVE ARTIFACT api

build:
    FROM +src
    WORKDIR /api/
    RUN cargo build -r
    SAVE ARTIFACT target/release/api

image:
    # FROM --platform=linux/amd64 gcr.io/distroless/static:nonroot
    # FROM debian:stable-20200803-slim
    FROM rust
    COPY +build/api  /usr/local/bin/
    ENTRYPOINT ["/usr/local/bin/api"]
    SAVE IMAGE api
